import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import jsxA11y from "eslint-plugin-jsx-a11y";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Accessibility (PLAN.md §3b). eslint-config-next already registers the
  // jsx-a11y *plugin* (re-registering it would throw "Cannot redefine
  // plugin"), but only enables a handful of its rules as warnings — so we
  // layer the full recommended *rules* on top, error-level.
  {
    name: "veganfind/jsx-a11y-recommended",
    rules: {
      ...jsxA11y.flatConfigs.recommended.rules,
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by scripts/copy-maplibre-worker.mjs — vendor code, not ours.
    "public/maplibre/**",
  ]),
]);

export default eslintConfig;
